# Generated by Django 5.1.2 on 2024-12-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_client_newsletter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletter",
            name="user",
        ),
        migrations.RemoveField(
            model_name="sendattempt",
            name="campaign",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Newsletter",
        ),
        migrations.DeleteModel(
            name="SendAttempt",
        ),
    ]
