# Generated by Django 5.1.2 on 2024-12-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0003_remove_newsletter_user_remove_sendattempt_campaign_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MailingAttempt",
            new_name="MailingAttempts",
        ),
    ]
