# Generated by Django 5.1.2 on 2024-12-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_avatar_user_country_user_phone_alter_user_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailCampaign",
        ),
    ]
